CREATE TABLE [dbo].[Protectors](
	[Id] [int] NOT NULL,
	[English name] [nvarchar](255) NULL,
	[sortId] [float] NULL,
	[Wandering Equip Id] [float] NULL,
	[vagrantItemLotId] [float] NULL,
	[vagrantBonusEneDropItemLotId] [float] NULL,
	[vagrantItemEneDropItemLotId] [float] NULL,
	[Repair Price] [float] NULL,
	[Basic Price] [float] NULL,
	[Sell Value] [float] NULL,
	[Weight (kg)] [float] NULL,
	[residentSpEffectId] [float] NULL,
	[residentSpEffectId2] [float] NULL,
	[residentSpEffectId3] [float] NULL,
	[materialSetId] [float] NULL,
	[partsDamageRate] [float] NULL,
	[corectSARecover] [float] NULL,
	[originEquipPro] [float] NULL,
	[originEquipPro1] [float] NULL,
	[originEquipPro2] [float] NULL,
	[originEquipPro3] [float] NULL,
	[originEquipPro4] [float] NULL,
	[originEquipPro5] [float] NULL,
	[originEquipPro6] [float] NULL,
	[originEquipPro7] [float] NULL,
	[originEquipPro8] [float] NULL,
	[originEquipPro9] [float] NULL,
	[originEquipPro10] [float] NULL,
	[originEquipPro11] [float] NULL,
	[originEquipPro12] [float] NULL,
	[originEquipPro13] [float] NULL,
	[originEquipPro14] [float] NULL,
	[originEquipPro15] [float] NULL,
	[faceScaleM_ScaleX] [float] NULL,
	[faceScaleM_ScaleZ] [float] NULL,
	[faceScaleM_MaxX] [float] NULL,
	[faceScaleM_MaxZ] [float] NULL,
	[faceScaleF_ScaleX] [float] NULL,
	[faceScaleF_ScaleZ] [float] NULL,
	[faceScaleF_MaxX] [float] NULL,
	[faceScaleF_MaxZ] [float] NULL,
	[qwcId] [float] NULL,
	[equipModelId] [float] NULL,
	[iconIdM] [float] NULL,
	[iconIdF] [float] NULL,
	[knockBack] [float] NULL,
	[knockbackBounceRate] [float] NULL,
	[durability] [float] NULL,
	[durabilityMax] [float] NULL,
	[saDurability] [float] NULL,
	[Defense Flick Power] [float] NULL,
	[Physical Defense] [float] NULL,
	[defenseMagic] [float] NULL,
	[defenseFire] [float] NULL,
	[defenseThunder] [float] NULL,
	[defenseSlash] [float] NULL,
	[defenseBlow] [float] NULL,
	[defenseThrust] [float] NULL,
	[resistPoison] [float] NULL,
	[resistDisease] [float] NULL,
	[resistBlood] [float] NULL,
	[resistCurse] [float] NULL,
	[reinforceTypeId] [float] NULL,
	[trophySGradeId] [float] NULL,
	[shopLv] [float] NULL,
	[knockbackParamId] [float] NULL,
	[Flick Damage Cut Rate] [float] NULL,
	[equipModelCategory] [float] NULL,
	[equipModelGender] [float] NULL,
	[protectorCategory] [float] NULL,
	[defenseMaterial] [float] NULL,
	[defenseMaterialSfx] [float] NULL,
	[partsDmgType] [float] NULL,
	[defenseMaterial_Weak] [float] NULL,
	[defenseMaterialSfx_Weak] [float] NULL,
	[isDeposit] [bit] NOT NULL,
	[headEquip] [bit] NOT NULL,
	[bodyEquip] [bit] NOT NULL,
	[armEquip] [bit] NOT NULL,
	[legEquip] [bit] NOT NULL,
	[useFaceScale] [bit] NOT NULL,
	[invisibleFlag00] [float] NULL,
	[invisibleFlag01] [float] NULL,
	[invisibleFlag02] [float] NULL,
	[invisibleFlag03] [float] NULL,
	[invisibleFlag04] [float] NULL,
	[invisibleFlag05] [float] NULL,
	[invisibleFlag06] [float] NULL,
	[invisibleFlag07] [float] NULL,
	[invisibleFlag08] [float] NULL,
	[invisibleFlag09] [float] NULL,
	[invisibleFlag10] [float] NULL,
	[invisibleFlag11] [float] NULL,
	[invisibleFlag12] [float] NULL,
	[invisibleFlag13] [float] NULL,
	[invisibleFlag14] [float] NULL,
	[invisibleFlag15] [float] NULL,
	[invisibleFlag16] [float] NULL,
	[invisibleFlag17] [float] NULL,
	[invisibleFlag18] [float] NULL,
	[invisibleFlag19] [float] NULL,
	[invisibleFlag20] [float] NULL,
	[invisibleFlag21] [float] NULL,
	[invisibleFlag22] [float] NULL,
	[invisibleFlag23] [float] NULL,
	[invisibleFlag24] [float] NULL,
	[invisibleFlag25] [float] NULL,
	[invisibleFlag26] [float] NULL,
	[invisibleFlag27] [float] NULL,
	[invisibleFlag28] [float] NULL,
	[invisibleFlag29] [float] NULL,
	[invisibleFlag30] [float] NULL,
	[invisibleFlag31] [float] NULL,
	[invisibleFlag32] [float] NULL,
	[invisibleFlag33] [float] NULL,
	[invisibleFlag34] [float] NULL,
	[invisibleFlag35] [float] NULL,
	[invisibleFlag36] [float] NULL,
	[invisibleFlag37] [float] NULL,
	[invisibleFlag38] [float] NULL,
	[invisibleFlag39] [float] NULL,
	[invisibleFlag40] [float] NULL,
	[invisibleFlag41] [float] NULL,
	[invisibleFlag42] [float] NULL,
	[invisibleFlag43] [float] NULL,
	[invisibleFlag44] [float] NULL,
	[invisibleFlag45] [float] NULL,
	[invisibleFlag46] [float] NULL,
	[invisibleFlag47] [float] NULL,
	[disableMultiDropShare] [bit] NOT NULL,
	[simpleModelForDlc] [bit] NOT NULL,
	[oldSortId] [float] NULL,
 CONSTRAINT [PK_Protectors] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

