CREATE TABLE [dbo].[Weapons](
	[Id] [int] NOT NULL,
	[BaseWeaponId] [int] NOT NULL,
	[InfusionId] [int] NOT NULL,
	[English name] [nvarchar](255) NULL,
	[Behavior Variation Id] [float] NULL,
	[Sort Id] [float] NULL,
	[Wandering Equip Id] [float] NULL,
	[Weight] [float] NOT NULL,
	[Weapon Weight Rate] [float] NOT NULL,
	[Repair Price] [float] NOT NULL,
	[Base Price] [float] NOT NULL,
	[Sell Value] [float] NOT NULL,
	[Correct Strength] [float] NOT NULL,
	[Correct Agility] [float] NOT NULL,
	[Correct Magic] [float] NOT NULL,
	[Correct Faith] [float] NOT NULL,
	[Physical Guard Percent] [float] NOT NULL,
	[Magical Guard Percent] [float] NOT NULL,
	[Fire Guard Percent] [float] NOT NULL,
	[Lightning Guard Percent] [float] NOT NULL,
	[Special Effect Behavior Id 0] [float] NOT NULL,
	[Special Effect Behavior Id 1] [float] NOT NULL,
	[Special Effect Behavior Id 2] [float] NOT NULL,
	[Resident Special Effect Id 0] [float] NOT NULL,
	[ResidentSpecial Effect Id 1] [float] NOT NULL,
	[Resident Special Effect Id 2] [float] NOT NULL,
	[Material Set Id] [float] NOT NULL,
	[Origin Weapon] [float] NOT NULL,
	[Origin Weapon +1] [float] NOT NULL,
	[Origin Weapon +2] [float] NOT NULL,
	[Origin Weapon +3] [float] NOT NULL,
	[Origin Weapon +4] [float] NOT NULL,
	[Origin Weapon +5] [float] NOT NULL,
	[Origin Weapon +6] [float] NOT NULL,
	[Origin Weapon +7] [float] NOT NULL,
	[Origin Weapon +8] [float] NOT NULL,
	[Origin Weapon +9] [float] NOT NULL,
	[Origin Weapon +10] [float] NOT NULL,
	[Origin Weapon +11] [float] NOT NULL,
	[Origin Weapon +12] [float] NOT NULL,
	[Origin Weapon +13] [float] NOT NULL,
	[Origin Weapon +14] [float] NOT NULL,
	[Origin Weapon +15] [float] NOT NULL,
	[antiDemonDamageRate] [float] NOT NULL,
	[antSaintDamageRate] [float] NOT NULL,
	[antWeakA_DamageRate] [float] NOT NULL,
	[antWeakB_DamageRate] [float] NOT NULL,
	[vagrantItemLotId] [float] NOT NULL,
	[vagrantBonusEneDropItemLotId] [float] NOT NULL,
	[vagrantItemEneDropItemLotId] [float] NOT NULL,
	[Model Id] [float] NOT NULL,
	[iconId] [float] NOT NULL,
	[Initial Durability] [float] NOT NULL,
	[Max Durability] [float] NOT NULL,
	[attackThrowEscape] [float] NOT NULL,
	[parryDamageLife] [float] NOT NULL,
	[Physical Damage] [float] NOT NULL,
	[Magic Damage] [float] NOT NULL,
	[Fire Damage] [float] NOT NULL,
	[Lightning Damage] [float] NOT NULL,
	[Stamina Damage] [float] NOT NULL,
	[saWeaponDamage] [float] NOT NULL,
	[saDurability] [float] NOT NULL,
	[guardAngle] [float] NOT NULL,
	[staminaGuardDef] [float] NOT NULL,
	[reinforceTypeId] [float] NOT NULL,
	[trophySGradeId] [float] NOT NULL,
	[trophySeqId] [float] NOT NULL,
	[throwAtkRate] [float] NOT NULL,
	[bowDistRate] [float] NOT NULL,
	[Equip Model Category] [float] NOT NULL,
	[Equip Model Gender] [float] NOT NULL,
	[Weapon Category] [float] NOT NULL,
	[Weapon Motion Category] [float] NOT NULL,
	[Guard Motion Category] [float] NOT NULL,
	[Attack Material] [float] NOT NULL,
	[Defend Material] [float] NOT NULL,
	[Defend Sfx Material] [float] NOT NULL,
	[Correct Type] [int] NOT NULL,
	[Special Attributes] [float] NOT NULL,
	[Special Attack Category] [float] NOT NULL,
	[Weapon Motion One Handed Id] [float] NOT NULL,
	[Weapon Motion Two Handed Id] [float] NOT NULL,
	[Required Strength] [float] NOT NULL,
	[Required Agility] [float] NOT NULL,
	[Required Magic] [float] NOT NULL,
	[Required Faith] [float] NOT NULL,
	[Over Strength] [float] NOT NULL,
	[Attack Base Parry] [float] NOT NULL,
	[Defense Base Parry] [float] NOT NULL,
	[Guard Base Repel] [float] NOT NULL,
	[Attack Base Repel] [float] NOT NULL,
	[Guard Cut Cancel Rate] [float] NOT NULL,
	[Guard Level] [float] NOT NULL,
	[Slash Guard Percent] [float] NOT NULL,
	[Blow Guard Percent] [float] NOT NULL,
	[Thrust Guard Percent] [float] NOT NULL,
	[Poison Guard Resist] [float] NOT NULL,
	[Disease Guard Resist] [float] NOT NULL,
	[Bleed Guard Resist] [float] NOT NULL,
	[Curse Guard Resist] [float] NOT NULL,
	[Is Durability Divergence] [float] NOT NULL,
	[Right Hand Equipable] [bit] NOT NULL,
	[Left Hand Equipable] [bit] NOT NULL,
	[Both Hand Equipable] [bit] NOT NULL,
	[Arrow Slot Equipable] [bit] NOT NULL,
	[Bolt Slot Equipable] [bit] NOT NULL,
	[Enable Guard] [bit] NOT NULL,
	[Enable Parry] [bit] NOT NULL,
	[Enable Magic] [bit] NOT NULL,
	[Enable Sorcery] [bit] NOT NULL,
	[Enable Pyromancy] [bit] NOT NULL,
	[Enable Vow Magic] [bit] NOT NULL,
	[Is Normal Attack Type] [bit] NOT NULL,
	[Is Blow Attack Type] [bit] NOT NULL,
	[Is Slash Attack Type] [bit] NOT NULL,
	[Is Thrust Attack Type] [bit] NOT NULL,
	[Is Enhanced] [bit] NOT NULL,
	[Is Luck Correct] [bit] NOT NULL,
	[Is Custom] [bit] NOT NULL,
	[Disable Base Change Reset] [bit] NOT NULL,
	[Disable Repair] [bit] NOT NULL,
	[Is Dark Hand] [bit] NOT NULL,
	[Simple Model For Dlc] [bit] NOT NULL,
	[Lantern Weapon] [bit] NOT NULL,
	[Is Versus Ghost Weapon] [bit] NOT NULL,
	[Base Change Category] [float] NULL,
	[Is Dragon Slayer] [bit] NOT NULL,
	[Is Deposit] [bit] NOT NULL,
	[Disable Multi Drop Share] [bit] NOT NULL,
	[Old Sort Id] [float] NULL,
	[English Type] [nvarchar](255) NULL,
 CONSTRAINT [PK_Weapons] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

