using System;
using System.Collections.Generic;

namespace DarkSoulsCore.Models
{
    public partial class Weapons
    {
        public int Id { get; set; }
        public int BaseWeaponId { get; set; }
        public string EnglishName { get; set; }
        public double? BehaviorVariationId { get; set; }
        public double? SortId { get; set; }
        public double? WanderingEquipId { get; set; }
        public double Weight { get; set; }
        public double WeaponWeightRate { get; set; }
        public double RepairPrice { get; set; }
        public double BasePrice { get; set; }
        public double SellValue { get; set; }
        public double CorrectStrength { get; set; }
        public double CorrectAgility { get; set; }
        public double CorrectMagic { get; set; }
        public double CorrectFaith { get; set; }
        public double PhysicalGuardPercent { get; set; }
        public double MagicalGuardPercent { get; set; }
        public double FireGuardPercent { get; set; }
        public double LightningGuardPercent { get; set; }
        public double SpecialEffectBehaviorId0 { get; set; }
        public double SpecialEffectBehaviorId1 { get; set; }
        public double SpecialEffectBehaviorId2 { get; set; }
        public double ResidentSpecialEffectId0 { get; set; }
        public double ResidentSpecialEffectId1 { get; set; }
        public double ResidentSpecialEffectId2 { get; set; }
        public double MaterialSetId { get; set; }
        public double OriginWeapon { get; set; }
        public double OriginWeapon1 { get; set; }
        public double OriginWeapon2 { get; set; }
        public double OriginWeapon3 { get; set; }
        public double OriginWeapon4 { get; set; }
        public double OriginWeapon5 { get; set; }
        public double OriginWeapon6 { get; set; }
        public double OriginWeapon7 { get; set; }
        public double OriginWeapon8 { get; set; }
        public double OriginWeapon9 { get; set; }
        public double OriginWeapon10 { get; set; }
        public double OriginWeapon11 { get; set; }
        public double OriginWeapon12 { get; set; }
        public double OriginWeapon13 { get; set; }
        public double OriginWeapon14 { get; set; }
        public double OriginWeapon15 { get; set; }
        public double AntiDemonDamageRate { get; set; }
        public double AntSaintDamageRate { get; set; }
        public double AntWeakADamageRate { get; set; }
        public double AntWeakBDamageRate { get; set; }
        public double VagrantItemLotId { get; set; }
        public double VagrantBonusEneDropItemLotId { get; set; }
        public double VagrantItemEneDropItemLotId { get; set; }
        public double ModelId { get; set; }
        public double IconId { get; set; }
        public double InitialDurability { get; set; }
        public double MaxDurability { get; set; }
        public double AttackThrowEscape { get; set; }
        public double ParryDamageLife { get; set; }
        public double PhysicalDamage { get; set; }
        public double MagicDamage { get; set; }
        public double FireDamage { get; set; }
        public double LightningDamage { get; set; }
        public double StaminaDamage { get; set; }
        public double SaWeaponDamage { get; set; }
        public double SaDurability { get; set; }
        public double GuardAngle { get; set; }
        public double StaminaGuardDef { get; set; }
        public int ReinforceTypeId { get; set; }
        public double TrophySgradeId { get; set; }
        public double TrophySeqId { get; set; }
        public double ThrowAtkRate { get; set; }
        public double BowDistRate { get; set; }
        public double EquipModelCategory { get; set; }
        public double EquipModelGender { get; set; }
        public double WeaponCategory { get; set; }
        public double WeaponMotionCategory { get; set; }
        public double GuardMotionCategory { get; set; }
        public double AttackMaterial { get; set; }
        public double DefendMaterial { get; set; }
        public double DefendSfxMaterial { get; set; }
        public int CorrectType { get; set; }
        public double SpecialAttributes { get; set; }
        public double SpecialAttackCategory { get; set; }
        public double WeaponMotionOneHandedId { get; set; }
        public double WeaponMotionTwoHandedId { get; set; }
        public double RequiredStrength { get; set; }
        public double RequiredAgility { get; set; }
        public double RequiredMagic { get; set; }
        public double RequiredFaith { get; set; }
        public double OverStrength { get; set; }
        public double AttackBaseParry { get; set; }
        public double DefenseBaseParry { get; set; }
        public double GuardBaseRepel { get; set; }
        public double AttackBaseRepel { get; set; }
        public double GuardCutCancelRate { get; set; }
        public double GuardLevel { get; set; }
        public double SlashGuardPercent { get; set; }
        public double BlowGuardPercent { get; set; }
        public double ThrustGuardPercent { get; set; }
        public double PoisonGuardResist { get; set; }
        public double DiseaseGuardResist { get; set; }
        public double BleedGuardResist { get; set; }
        public double CurseGuardResist { get; set; }
        public double IsDurabilityDivergence { get; set; }
        public bool RightHandEquipable { get; set; }
        public bool LeftHandEquipable { get; set; }
        public bool BothHandEquipable { get; set; }
        public bool ArrowSlotEquipable { get; set; }
        public bool BoltSlotEquipable { get; set; }
        public bool EnableGuard { get; set; }
        public bool EnableParry { get; set; }
        public bool EnableMagic { get; set; }
        public bool EnableSorcery { get; set; }
        public bool EnablePyromancy { get; set; }
        public bool EnableVowMagic { get; set; }
        public bool IsNormalAttackType { get; set; }
        public bool IsBlowAttackType { get; set; }
        public bool IsSlashAttackType { get; set; }
        public bool IsThrustAttackType { get; set; }
        public bool IsEnhanced { get; set; }
        public bool IsLuckCorrect { get; set; }
        public bool IsCustom { get; set; }
        public bool DisableBaseChangeReset { get; set; }
        public bool DisableRepair { get; set; }
        public bool IsDarkHand { get; set; }
        public bool SimpleModelForDlc { get; set; }
        public bool LanternWeapon { get; set; }
        public bool IsVersusGhostWeapon { get; set; }
        public double? BaseChangeCategory { get; set; }
        public bool IsDragonSlayer { get; set; }
        public bool IsDeposit { get; set; }
        public bool DisableMultiDropShare { get; set; }
        public double? OldSortId { get; set; }
        public string EnglishType { get; set; }
    }
}
