using System;
using System.Collections.Generic;

namespace DarkSoulsReact.Models
{
    public partial class Protectors
    {
        public int Id { get; set; }
        public string EnglishName { get; set; }
        public double? SortId { get; set; }
        public double? WanderingEquipId { get; set; }
        public double? VagrantItemLotId { get; set; }
        public double? VagrantBonusEneDropItemLotId { get; set; }
        public double? VagrantItemEneDropItemLotId { get; set; }
        public double? RepairPrice { get; set; }
        public double? BasicPrice { get; set; }
        public double? SellValue { get; set; }
        public double? WeightKg { get; set; }
        public double? ResidentSpEffectId { get; set; }
        public double? ResidentSpEffectId2 { get; set; }
        public double? ResidentSpEffectId3 { get; set; }
        public double? MaterialSetId { get; set; }
        public double? PartsDamageRate { get; set; }
        public double? CorectSarecover { get; set; }
        public double? OriginEquipPro { get; set; }
        public double? OriginEquipPro1 { get; set; }
        public double? OriginEquipPro2 { get; set; }
        public double? OriginEquipPro3 { get; set; }
        public double? OriginEquipPro4 { get; set; }
        public double? OriginEquipPro5 { get; set; }
        public double? OriginEquipPro6 { get; set; }
        public double? OriginEquipPro7 { get; set; }
        public double? OriginEquipPro8 { get; set; }
        public double? OriginEquipPro9 { get; set; }
        public double? OriginEquipPro10 { get; set; }
        public double? OriginEquipPro11 { get; set; }
        public double? OriginEquipPro12 { get; set; }
        public double? OriginEquipPro13 { get; set; }
        public double? OriginEquipPro14 { get; set; }
        public double? OriginEquipPro15 { get; set; }
        public double? FaceScaleMScaleX { get; set; }
        public double? FaceScaleMScaleZ { get; set; }
        public double? FaceScaleMMaxX { get; set; }
        public double? FaceScaleMMaxZ { get; set; }
        public double? FaceScaleFScaleX { get; set; }
        public double? FaceScaleFScaleZ { get; set; }
        public double? FaceScaleFMaxX { get; set; }
        public double? FaceScaleFMaxZ { get; set; }
        public double? QwcId { get; set; }
        public double? EquipModelId { get; set; }
        public double? IconIdM { get; set; }
        public double? IconIdF { get; set; }
        public double? KnockBack { get; set; }
        public double? KnockbackBounceRate { get; set; }
        public double? Durability { get; set; }
        public double? DurabilityMax { get; set; }
        public double? SaDurability { get; set; }
        public double? DefenseFlickPower { get; set; }
        public double? PhysicalDefense { get; set; }
        public double? DefenseMagic { get; set; }
        public double? DefenseFire { get; set; }
        public double? DefenseThunder { get; set; }
        public double? DefenseSlash { get; set; }
        public double? DefenseBlow { get; set; }
        public double? DefenseThrust { get; set; }
        public double? ResistPoison { get; set; }
        public double? ResistDisease { get; set; }
        public double? ResistBlood { get; set; }
        public double? ResistCurse { get; set; }
        public double? ReinforceTypeId { get; set; }
        public double? TrophySgradeId { get; set; }
        public double? ShopLv { get; set; }
        public double? KnockbackParamId { get; set; }
        public double? FlickDamageCutRate { get; set; }
        public double? EquipModelCategory { get; set; }
        public double? EquipModelGender { get; set; }
        public double? ProtectorCategory { get; set; }
        public double? DefenseMaterial { get; set; }
        public double? DefenseMaterialSfx { get; set; }
        public double? PartsDmgType { get; set; }
        public double? DefenseMaterialWeak { get; set; }
        public double? DefenseMaterialSfxWeak { get; set; }
        public bool IsDeposit { get; set; }
        public bool HeadEquip { get; set; }
        public bool BodyEquip { get; set; }
        public bool ArmEquip { get; set; }
        public bool LegEquip { get; set; }
        public bool UseFaceScale { get; set; }
        public double? InvisibleFlag00 { get; set; }
        public double? InvisibleFlag01 { get; set; }
        public double? InvisibleFlag02 { get; set; }
        public double? InvisibleFlag03 { get; set; }
        public double? InvisibleFlag04 { get; set; }
        public double? InvisibleFlag05 { get; set; }
        public double? InvisibleFlag06 { get; set; }
        public double? InvisibleFlag07 { get; set; }
        public double? InvisibleFlag08 { get; set; }
        public double? InvisibleFlag09 { get; set; }
        public double? InvisibleFlag10 { get; set; }
        public double? InvisibleFlag11 { get; set; }
        public double? InvisibleFlag12 { get; set; }
        public double? InvisibleFlag13 { get; set; }
        public double? InvisibleFlag14 { get; set; }
        public double? InvisibleFlag15 { get; set; }
        public double? InvisibleFlag16 { get; set; }
        public double? InvisibleFlag17 { get; set; }
        public double? InvisibleFlag18 { get; set; }
        public double? InvisibleFlag19 { get; set; }
        public double? InvisibleFlag20 { get; set; }
        public double? InvisibleFlag21 { get; set; }
        public double? InvisibleFlag22 { get; set; }
        public double? InvisibleFlag23 { get; set; }
        public double? InvisibleFlag24 { get; set; }
        public double? InvisibleFlag25 { get; set; }
        public double? InvisibleFlag26 { get; set; }
        public double? InvisibleFlag27 { get; set; }
        public double? InvisibleFlag28 { get; set; }
        public double? InvisibleFlag29 { get; set; }
        public double? InvisibleFlag30 { get; set; }
        public double? InvisibleFlag31 { get; set; }
        public double? InvisibleFlag32 { get; set; }
        public double? InvisibleFlag33 { get; set; }
        public double? InvisibleFlag34 { get; set; }
        public double? InvisibleFlag35 { get; set; }
        public double? InvisibleFlag36 { get; set; }
        public double? InvisibleFlag37 { get; set; }
        public double? InvisibleFlag38 { get; set; }
        public double? InvisibleFlag39 { get; set; }
        public double? InvisibleFlag40 { get; set; }
        public double? InvisibleFlag41 { get; set; }
        public double? InvisibleFlag42 { get; set; }
        public double? InvisibleFlag43 { get; set; }
        public double? InvisibleFlag44 { get; set; }
        public double? InvisibleFlag45 { get; set; }
        public double? InvisibleFlag46 { get; set; }
        public double? InvisibleFlag47 { get; set; }
        public bool DisableMultiDropShare { get; set; }
        public bool SimpleModelForDlc { get; set; }
        public double? OldSortId { get; set; }
    }
}
